<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Fasilitas_laundry extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Fasilitas_laundry_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'fasilitas_laundry/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'fasilitas_laundry/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'fasilitas_laundry/index.html';
            $config['first_url'] = base_url() . 'fasilitas_laundry/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Fasilitas_laundry_model->total_rows($q);
        $fasilitas_laundry = $this->Fasilitas_laundry_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'fasilitas_laundry_data' => $fasilitas_laundry,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('fasilitas_laundry/fasilitas_laundry_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Fasilitas_laundry_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_fasilitas' => $row->id_fasilitas,
		'id_lokasi' => $row->id_lokasi,
	    );
            $this->load->view('fasilitas_laundry/fasilitas_laundry_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('fasilitas_laundry'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('fasilitas_laundry/create_action'),
	    'id_fasilitas' => set_value('id_fasilitas'),
	    'id_lokasi' => set_value('id_lokasi'),
	);
        $this->load->view('fasilitas_laundry/fasilitas_laundry_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
	    );

            $this->Fasilitas_laundry_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('fasilitas_laundry'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Fasilitas_laundry_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('fasilitas_laundry/update_action'),
		'id_fasilitas' => set_value('id_fasilitas', $row->id_fasilitas),
		'id_lokasi' => set_value('id_lokasi', $row->id_lokasi),
	    );
            $this->load->view('fasilitas_laundry/fasilitas_laundry_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('fasilitas_laundry'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_fasilitas', TRUE));
        } else {
            $data = array(
	    );

            $this->Fasilitas_laundry_model->update($this->input->post('id_fasilitas', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('fasilitas_laundry'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Fasilitas_laundry_model->get_by_id($id);

        if ($row) {
            $this->Fasilitas_laundry_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('fasilitas_laundry'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('fasilitas_laundry'));
        }
    }

    public function _rules() 
    {

	$this->form_validation->set_rules('id_fasilitas', 'id_fasilitas', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Fasilitas_laundry.php */
/* Location: ./application/controllers/Fasilitas_laundry.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-07-06 03:00:38 */
/* http://harviacode.com */